name: tests
on: [push, pull_request]

jobs:
  
  testing:
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Environment (Bun latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Linting
        run: bun x ts-standard --fix

      - name: Run tests
        run: bun run test
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379